version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 97221991
      POSTGRES_DB: Capstone

  backend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
